version: "3"

networks:
  redis-net: {}

volumes:
  redis-vol: {}

services:
  redis:
    image: redis:alpine
    command:
      - redis-server
      - --appendonly yes
      - --requirepass $$REDISCLI_AUTH
    environment:
      REDISCLI_AUTH: secret@123
    networks:
      - redis-net
    restart: unless-stopped
    volumes:
      - redis-vol:/data
    healthcheck:
      test: redis-cli -h redis -p 6379 ping
      start_period: 1s
      interval: 1s
      timeout: 3s
      retries: 10

  laravel-echo-server:
    image: oanhnn/laravel-echo-server:3.1
    depends_on:
      - redis
    environment:
      LARAVEL_ECHO_SERVER_AUTH_HOST: http://example.com
      LARAVEL_ECHO_SERVER_DEBUG:     'true'
      LARAVEL_ECHO_SERVER_DB:        redis
      REDIS_HOST:     redis
      REDIS_PORT:     6379
      REDIS_PREFIX:   laravel_
      REDIS_PASSWORD: secret@123
      REDIS_DB:       0
    networks:
      - redis-net
    ports:
      - 6001:6001
    restart: unless-stopped
    healthcheck:
      test: /usr/local/bin/health-check
      start_period: 1s
      interval: 1s
      timeout: 3s
      retries: 10
